In [ ]:
import pandas as pd

In [ ]:
file_path = '/content/drive/MyDrive/NASDAQ_100_2020-2025.xlsm'
xls = pd.ExcelFile(file_path)

In [ ]:
for sheet_name in xls.sheet_names[1:]:
  df = pd.read_excel(xls, sheet_name=sheet_name)

In [ ]:
tickers_list = []
df2 = pd.read_excel(xls, sheet_name='Companies')
for ticker in df2['Ticker']:
  tickers_list.append(ticker)

In [ ]:
tickers_list = [ticker for ticker in tickers_list if ticker not in ['ARM UW Equity', 'DASH UW Equity', 'LIN UW Equity', 'PLTR UW Equity']]

In [ ]:
ticker_data={}
for sheet_name in xls.sheet_names[1:]:
    # Load the sheet data (each sheet is a ticker)
  df = pd.read_excel(xls, sheet_name=sheet_name, skiprows = 5)
  if 'Dates' not in df.columns or 'PX_LAST' not in df.columns:
      print(f"Sheet {sheet_name} is missing 'Dates' or 'PX_LAST' column.")
      continue
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
  if pd.isna(df.loc[0, 'Dates']) or df.loc[0, 'Dates'] != pd.Timestamp('2020-04-03'):
    print("First date is incorrect. Replacing with 2020-04-03.")
    df.loc[0, 'Dates'] = pd.Timestamp('2020-04-03')
  ticker_data[sheet_name] = df

<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')

First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.

<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')

First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.

<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')

First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.

<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')

First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.

<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')

First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.

<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')

First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.

<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')

First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.

<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')

First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.

<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')

First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.

<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')

First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.

<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')

First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.

<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')

First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.

<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')

First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.

<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')

First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.

<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')

First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.

<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')

First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.

<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')

First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.
First date is incorrect. Replacing with 2020-04-03.

<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')
<ipython-input-6-1f7d7e5d6e4e>:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dates'] = pd.to_datetime(df['Dates'], errors='coerce')

In [ ]:
tickers_to_remove = ['ARM UW Equity', 'DASH UW Equity', 'LIN UW Equity', 'PLTR UW Equity']

for ticker in tickers_to_remove:
    if ticker in ticker_data:
        del ticker_data[ticker]

In [ ]:
ticker_data['WBD UW Equity']

         Dates  PX_LAST  LAST_PRICE  CUR_MKT_CAP
0   2020-04-03      NaN         NaN   12611.1964
1   2020-04-10      NaN         NaN   14931.2065
2   2020-04-17      NaN         NaN   15187.8744
3   2020-04-24      NaN         NaN   14538.0334
4   2020-05-01      NaN         NaN   16071.9713
..         ...      ...         ...          ...
262 2025-04-11     7.97        7.97   19716.4698
263 2025-04-18     8.11        8.11   20062.8068
264 2025-04-25     8.59        8.59   21250.2479
265 2025-05-02     8.54        8.54   21126.5561
266 2025-05-09     9.07        9.07   22439.8603

[267 rows x 4 columns]

In [ ]:
missing_values_count = {}

# Loop through each DataFrame and count missing values in column 'A'
for ticker, df in ticker_data.items():
    if 'PX_LAST' in df.columns:  # Ensure column A exists
        missing_values_count[ticker] = df['PX_LAST'].isna().sum()
    else:
        missing_values_count[ticker] = 'Column A not found'

# Displaying the missing values count for each ticker
missing_values_count

{'ADBE UW Equity': np.int64(0),
 'AMD UW Equity': np.int64(0),
 'ABNB UW Equity': np.int64(36),
 'AAPL UW Equity': np.int64(0),
 'ADI UW Equity': np.int64(0),
 'ADP UW Equity': np.int64(0),
 'ADSK UW Equity': np.int64(0),
 'AEP UW Equity': np.int64(26),
 'AMAT UW Equity': np.int64(0),
 'AMGN UW Equity': np.int64(0),
 'AMZN UW Equity': np.int64(0),
 'ANSS UW Equity': np.int64(0),
 'APP UW Equity': np.int64(54),
 'ASML UW Equity': np.int64(0),
 'AVGO UW Equity': np.int64(0),
 'AXON UW Equity': np.int64(0),
 'AZN UW Equity': np.int64(25),
 'BIIB UW Equity': np.int64(0),
 'BKNG UW Equity': np.int64(0),
 'BKR UW Equity': np.int64(88),
 'CCEP UW Equity': np.int64(76),
 'CDNS UW Equity': np.int64(0),
 'CDW UW Equity': np.int64(0),
 'CEG UW Equity': np.int64(94),
 'CHTR UW Equity': np.int64(0),
 'CMCSA UW Equity': np.int64(0),
 'COST UW Equity': np.int64(0),
 'CPRT UW Equity': np.int64(0),
 'CRWD UW Equity': np.int64(0),
 'CSCO UW Equity': np.int64(0),
 'CSGP UW Equity': np.int64(0),
 'CSX UW Equity': np.int64(0),
 'CTAS UW Equity': np.int64(0),
 'CTSH UW Equity': np.int64(0),
 'DDOG UW Equity': np.int64(0),
 'DXCM UW Equity': np.int64(0),
 'EA UW Equity': np.int64(0),
 'EXC UW Equity': np.int64(0),
 'FANG UW Equity': np.int64(0),
 'FAST UW Equity': np.int64(0),
 'FTNT UW Equity': np.int64(0),
 'GEHC UW Equity': np.int64(141),
 'GFS UW Equity': np.int64(82),
 'GILD UW Equity': np.int64(0),
 'GOOG UW Equity': np.int64(0),
 'GOOGL UW Equity': np.int64(0),
 'HON UW Equity': np.int64(58),
 'IDXX UW Equity': np.int64(0),
 'INTC UW Equity': np.int64(0),
 'INTU UW Equity': np.int64(0),
 'ISRG UW Equity': np.int64(0),
 'KDP UW Equity': np.int64(25),
 'KHC UW Equity': np.int64(0),
 'KLAC UW Equity': np.int64(0),
 'LRCX UW Equity': np.int64(0),
 'LULU UW Equity': np.int64(0),
 'MAR UW Equity': np.int64(0),
 'MCHP UW Equity': np.int64(0),
 'MDB UQ Equity': np.int64(0),
 'MDLZ UW Equity': np.int64(0),
 'MELI UW Equity': np.int64(0),
 'META UW Equity': np.int64(0),
 'MNST UW Equity': np.int64(0),
 'MRVL UW Equity': np.int64(0),
 'MSFT UW Equity': np.int64(0),
 'MSTR UW Equity': np.int64(0),
 'MU UW Equity': np.int64(0),
 'NFLX UW Equity': np.int64(0),
 'NVDA UW Equity': np.int64(0),
 'NXPI UW Equity': np.int64(0),
 'ODFL UW Equity': np.int64(0),
 'ON UW Equity': np.int64(0),
 'ORLY UW Equity': np.int64(0),
 'PANW UW Equity': np.int64(82),
 'PAYX UW Equity': np.int64(0),
 'PCAR UW Equity': np.int64(0),
 'PDD UW Equity': np.int64(0),
 'PEP UW Equity': np.int64(0),
 'PYPL UW Equity': np.int64(0),
 'QCOM UW Equity': np.int64(0),
 'REGN UW Equity': np.int64(0),
 'ROP UW Equity': np.int64(170),
 'ROST UW Equity': np.int64(0),
 'SBUX UW Equity': np.int64(0),
 'SNPS UW Equity': np.int64(0),
 'TEAM UW Equity': np.int64(0),
 'TMUS UW Equity': np.int64(0),
 'TSLA UW Equity': np.int64(0),
 'TTD UQ Equity': np.int64(0),
 'TTWO UW Equity': np.int64(0),
 'TXN UW Equity': np.int64(0),
 'VRSK UW Equity': np.int64(0),
 'VRTX UW Equity': np.int64(0),
 'WBD UW Equity': np.int64(105),
 'WDAY UW Equity': np.int64(0),
 'XEL UW Equity': np.int64(0),
 'ZS UW Equity': np.int64(0)}

serious : ARM UW Equity, BKR UW Equity, CCEP UW Equity, CEG UW Equity,DASH UW Equity, GEHC UW Equity, GFS UW Equity, HON UW Equity', LIN UW Equity, PANW UW Equity, PLTR UW Equity, ROP UW Equity, WBD UW Equity

In [ ]:
for ticker, df in ticker_data.items():
    df['PX_LAST'].fillna(df['PX_LAST'].mean(), inplace=True)

<ipython-input-10-34707c62f31f>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['PX_LAST'].fillna(df['PX_LAST'].mean(), inplace=True)

In [ ]:
for ticker, df in ticker_data.items():
    df['returns'] = df['PX_LAST'].pct_change()

In [ ]:
cleaned_tickers = [
    ticker.split(' UW Equity')[0].split(' UQ Equity')[0]
    for ticker in tickers_list]

In [ ]:
# cleaned_tickers = [ticker.split(' UW Equity')[0] for ticker in tickers_list]
cleaned_tickers  ### tickers with UW Equit removed

['ADBE',
 'AMD',
 'ABNB',
 'GOOG',
 'GOOGL',
 'AMZN',
 'AEP',
 'AMGN',
 'ADI',
 'ANSS',
 'AAPL',
 'AMAT',
 'APP',
 'ASML',
 'AZN',
 'TEAM',
 'ADSK',
 'ADP',
 'AXON',
 'BKR',
 'BIIB',
 'BKNG',
 'AVGO',
 'CDNS',
 'CDW',
 'CHTR',
 'CTAS',
 'CSCO',
 'CCEP',
 'CTSH',
 'CMCSA',
 'CEG',
 'CPRT',
 'CSGP',
 'COST',
 'CRWD',
 'CSX',
 'DDOG',
 'DXCM',
 'FANG',
 'EA',
 'EXC',
 'FAST',
 'FTNT',
 'GEHC',
 'GILD',
 'GFS',
 'HON',
 'IDXX',
 'INTC',
 'INTU',
 'ISRG',
 'KDP',
 'KLAC',
 'KHC',
 'LRCX',
 'LULU',
 'MAR',
 'MRVL',
 'MELI',
 'META',
 'MCHP',
 'MU',
 'MSFT',
 'MSTR',
 'MDLZ',
 'MDB',
 'MNST',
 'NFLX',
 'NVDA',
 'NXPI',
 'ORLY',
 'ODFL',
 'ON',
 'PCAR',
 'PANW',
 'PAYX',
 'PYPL',
 'PDD',
 'PEP',
 'QCOM',
 'REGN',
 'ROP',
 'ROST',
 'SBUX',
 'SNPS',
 'TMUS',
 'TTWO',
 'TSLA',
 'TXN',
 'TTD',
 'VRSK',
 'VRTX',
 'WBD',
 'WDAY',
 'XEL',
 'ZS']

In [ ]:
import pandas as pd
import yfinance as yf

# Sample list of tickers (replace with your 100 tickers)
# tickers = ['AAPL', 'MSFT', 'GOOGL', 'TSLA', 'AMZN']

# Dictionary to store stock characteristics
characteristics = {
    'Ticker': [],
    'Sector': [],
    'industry': [],
    'Market Cap Category': []
}

# Loop through each ticker
for ticker in cleaned_tickers:
    stock = yf.Ticker(ticker)
    info = stock.info

    # Collecting sector and market cap
    characteristics['Ticker'].append(ticker)
    characteristics['Sector'].append(info.get('sector', 'Unknown'))
    characteristics['industry'].append(info.get('industry', 'Unknown'))
    # Market Cap classification
    market_cap = info.get('marketCap', 0)
    # characteristics['Market Cap'].append(market_cap)

    if market_cap >= 10e9:
        characteristics['Market Cap Category'].append('Large Cap')
    elif 2e9 <= market_cap < 10e9:
        characteristics['Market Cap Category'].append('Mid Cap')
    else:
        characteristics['Market Cap Category'].append('Small Cap')

# Convert the dictionary to a DataFrame
characteristics_df = pd.DataFrame(characteristics)
print(characteristics_df)

   Ticker                  Sector                        industry  \
0    ADBE              Technology          Software - Application
1     AMD              Technology                  Semiconductors
2    ABNB       Consumer Cyclical                 Travel Services
3    GOOG  Communication Services  Internet Content & Information
4   GOOGL  Communication Services  Internet Content & Information
..    ...                     ...                             ...
92   VRTX              Healthcare                   Biotechnology
93    WBD  Communication Services                   Entertainment
94   WDAY              Technology          Software - Application
95    XEL               Utilities  Utilities - Regulated Electric
96     ZS              Technology       Software - Infrastructure

   Market Cap Category
0            Large Cap
1            Large Cap
2            Large Cap
3            Large Cap
4            Large Cap
..                 ...
92           Large Cap
93           Large Cap
94           Large Cap
95           Large Cap
96           Large Cap

[97 rows x 4 columns]

In [ ]:
sector_counts = characteristics_df['Sector'].value_counts()
industry_counts = characteristics_df['industry'].value_counts()
market_cap_counts = characteristics_df['Market Cap Category'].value_counts()

# Displaying the counts for each column
print("Sector Counts:\n", sector_counts)
print("\nIndustry Counts:\n", industry_counts)
print("\nMarket Cap Category Counts:\n", market_cap_counts)

Sector Counts:
 Sector
Technology                42
Consumer Cyclical         11
Communication Services    10
Healthcare                10
Industrials                9
Consumer Defensive         7
Utilities                  4
Energy                     2
Real Estate                1
Financial Services         1
Name: count, dtype: int64

Industry Counts:
 industry
Software - Application                 14
Semiconductors                         13
Software - Infrastructure               7
Semiconductor Equipment & Materials     4
Beverages - Non-Alcoholic               4
Drug Manufacturers - General            4
Utilities - Regulated Electric          3
Telecom Services                        3
Internet Content & Information          3
Internet Retail                         3
Biotechnology                           2
Information Technology Services         2
Travel Services                         2
Specialty Business Services             2
Electronic Gaming & Multimedia          2
Entertainment                           2
Apparel Retail                          2
Consumer Electronics                    1
Aerospace & Defense                     1
Real Estate Services                    1
Railroads                               1
Discount Stores                         1
Medical Devices                         1
Utilities - Renewable                   1
Oil & Gas Equipment & Services          1
Communication Equipment                 1
Health Information Services             1
Industrial Distribution                 1
Oil & Gas E&P                           1
Conglomerates                           1
Packaged Foods                          1
Medical Instruments & Supplies          1
Lodging                                 1
Diagnostics & Research                  1
Confectioners                           1
Auto Parts                              1
Farm & Heavy Construction Machinery     1
Trucking                                1
Credit Services                         1
Restaurants                             1
Auto Manufacturers                      1
Consulting Services                     1
Name: count, dtype: int64

Market Cap Category Counts:
 Market Cap Category
Large Cap    97
Name: count, dtype: int64

In [ ]:
industry_mapping = {
    'Software - Application': 'Software & Technology',
    'Software - Infrastructure': 'Software & Technology',
    'Information Technology Services': 'Software & Technology',
    'Semiconductors': 'Semiconductors',
    'Semiconductor Equipment & Materials': 'Semiconductors',
    'Beverages - Non-Alcoholic': 'Consumer Staples',
    'Packaged Foods': 'Consumer Staples',
    'Confectioners': 'Consumer Staples',
    'Drug Manufacturers - General': 'Pharmaceuticals & Healthcare',
    'Biotechnology': 'Pharmaceuticals & Healthcare',
    'Diagnostics & Research': 'Pharmaceuticals & Healthcare',
    'Medical Devices': 'Pharmaceuticals & Healthcare',
    'Medical Instruments & Supplies': 'Pharmaceuticals & Healthcare',
    'Health Information Services': 'Pharmaceuticals & Healthcare',
    'Utilities - Regulated Electric': 'Utilities',
    'Utilities - Renewable': 'Utilities',
    'Telecom Services': 'Communication & Internet Services',
    'Communication Equipment': 'Communication & Internet Services',
    'Internet Content & Information': 'Communication & Internet Services',
    'Internet Retail': 'Communication & Internet Services',
    'Electronic Gaming & Multimedia': 'Media & Entertainment',
    'Entertainment': 'Media & Entertainment',
    'Media & Entertainment': 'Media & Entertainment',
    'Travel Services': 'Travel & Leisure',
    'Lodging': 'Travel & Leisure',
    'Airlines': 'Travel & Leisure',
    'Consumer Electronics': 'Consumer Discretionary',
    'Credit Services': 'Consumer Discretionary',
    'Auto Parts': 'Consumer Discretionary',
    'Auto Manufacturers': 'Consumer Discretionary',
    'Discount Stores': 'Consumer Discretionary',
    'Specialty Retail': 'Consumer Discretionary',
    'Aerospace & Defense': 'Industrials',
    'Industrial Distribution': 'Industrials',
    'Farm & Heavy Construction Machinery': 'Industrials',
    'Trucking': 'Industrials',
    'Railroads': 'Industrials',
    'Real Estate Services': 'Real Estate',
    'Oil & Gas Equipment & Services': 'Energy',
    'Oil & Gas E&P': 'Energy'
}

characteristics_df['industry'] = characteristics_df['industry'].map(industry_mapping).fillna(characteristics_df['industry'])
characteristics_df

,Ticker,Sector,industry,Market Cap Category
0,ADBE,Technology,Software & Technology,Large Cap
1,AMD,Technology,Semiconductors,Large Cap
2,ABNB,Consumer Cyclical,Travel & Leisure,Large Cap
3,GOOG,Communication Services,Communication & Internet Services,Large Cap
4,GOOGL,Communication Services,Communication & Internet Services,Large Cap
...,...,...,...,...
92,VRTX,Healthcare,Pharmaceuticals & Healthcare,Large Cap
93,WBD,Communication Services,Media & Entertainment,Large Cap
94,WDAY,Technology,Software & Technology,Large Cap
95,XEL,Utilities,Utilities,Large Cap
96,ZS,Technology,Software & Technology,Large Cap

In [ ]:
industry_mapping.update({
    'Specialty Business Services': 'Business Services',
    'Apparel Retail': 'Consumer Discretionary',
    'Conglomerates': 'Industrials',
    'Restaurants': 'Consumer Staples',
    'Consulting Services': 'Business Services'
})
characteristics_df['industry'] = characteristics_df['industry'].map(industry_mapping).fillna(characteristics_df['industry'])
characteristics_df

,Ticker,Sector,industry,Market Cap Category
0,ADBE,Technology,Software & Technology,Large Cap
1,AMD,Technology,Semiconductors,Large Cap
2,ABNB,Consumer Cyclical,Travel & Leisure,Large Cap
3,GOOG,Communication Services,Communication & Internet Services,Large Cap
4,GOOGL,Communication Services,Communication & Internet Services,Large Cap
...,...,...,...,...
92,VRTX,Healthcare,Pharmaceuticals & Healthcare,Large Cap
93,WBD,Communication Services,Media & Entertainment,Large Cap
94,WDAY,Technology,Software & Technology,Large Cap
95,XEL,Utilities,Utilities,Large Cap
96,ZS,Technology,Software & Technology,Large Cap

In [ ]:
industry_counts = characteristics_df['industry'].value_counts()
industry_counts

industry
Software & Technology                23
Semiconductors                       17
Communication & Internet Services    10
Pharmaceuticals & Healthcare         10
Consumer Discretionary                7
Consumer Staples                      7
Industrials                           6
Media & Entertainment                 4
Utilities                             4
Travel & Leisure                      3
Business Services                     3
Energy                                2
Real Estate                           1
Name: count, dtype: int64

In [ ]:
import pandas as pd

# Sample DataFrame (replace with your actual DataFrame)
# characteristics_df = pd.DataFrame({
#     'Ticker': ['AAPL', 'MSFT', 'GOOGL', 'TSLA', 'AMZN'],
#     'Sector': ['Technology', 'Technology', 'Communication Services', 'Consumer Discretionary', 'Consumer Discretionary'],
#     'Industry': ['Software & Technology', 'Software & Technology', 'Communication & Internet Services', 'Automotive', 'E-Commerce']
# })

# Creating a list of all unique sectors and industries
unique_sectors = characteristics_df['Sector'].unique().tolist()
unique_industries = characteristics_df['industry'].unique().tolist()

# Creating a new DataFrame with tickers as rows and sector/industry as columns (all zeros)
sector_industry_df = pd.DataFrame(index=characteristics_df['Ticker'], columns=unique_sectors + unique_industries)
sector_industry_df = sector_industry_df.fillna(0)

# Assigning 1 for each ticker that belongs to a sector or industry
for index, row in characteristics_df.iterrows():
    ticker = row['Ticker']
    sector = row['Sector']
    industry = row['industry']

    sector_industry_df.loc[ticker, sector] = 1
    sector_industry_df.loc[ticker, industry] = 1

# Displaying the sector-industry matrix
sector_industry_df

<ipython-input-19-8220926d18ba>:16: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  sector_industry_df = sector_industry_df.fillna(0)

,Technology,Consumer Cyclical,Communication Services,Utilities,Healthcare,Industrials,Energy,Consumer Defensive,Real Estate,Financial Services,...,Communication & Internet Services,Utilities,Pharmaceuticals & Healthcare,Consumer Discretionary,Industrials,Energy,Business Services,Consumer Staples,Real Estate,Media & Entertainment
Ticker,,,,,,,,,,,,,,,,,,,,,
ADBE,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AMD,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ABNB,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GOOG,0,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
GOOGL,0,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VRTX,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
WBD,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
WDAY,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
XEL,0,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
ZS,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# sector_industry_df.to_excel("Sector_Industry_Matrix.xlsx", index=True)

In [ ]:
ticker_data

{'ADBE UW Equity':          Dates  PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03   293.61      293.61  141461.5476       NaN
 1   2020-04-10   318.70      318.70  153549.9309  0.085453
 2   2020-04-17   344.11      344.11  165792.4905  0.079730
 3   2020-04-24   344.10      344.10  165787.6725 -0.000029
 4   2020-05-01   343.84      343.84  165662.4043 -0.000756
 ..         ...      ...         ...          ...       ...
 262 2025-04-11   352.47      352.47  150222.7140  0.009740
 263 2025-04-18   348.80      348.80  148658.5600 -0.010412
 264 2025-04-25   367.72      367.72  156722.2640  0.054243
 265 2025-05-02   380.87      380.87  162326.7940  0.035761
 266 2025-05-09   383.28      383.28  163353.9360  0.006328

 [267 rows x 5 columns],
 'AMD UW Equity':          Dates  PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03   42.590      42.590   49866.5993       NaN
 1   2020-04-10   48.380      48.380   56645.8341  0.135947
 2   2020-04-17   56.600      56.600   66270.2400  0.169905
 3   2020-04-24   56.180      56.180   65778.4820 -0.007420
 4   2020-05-01   49.880      49.880   58418.9770 -0.112140
 ..         ...      ...         ...          ...       ...
 262 2025-04-11   93.400      93.400  151740.7569  0.089086
 263 2025-04-18   87.500      87.500  142155.4200 -0.063169
 264 2025-04-25   96.645      96.645  157012.6921  0.104514
 265 2025-05-02   98.800      98.800  160513.7771  0.022298
 266 2025-05-09  102.840     102.840  166745.2074  0.040891

 [267 rows x 5 columns],
 'ABNB UW Equity':          Dates     PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03  139.213139         NaN          NaN       NaN
 1   2020-04-10  139.213139         NaN          NaN  0.000000
 2   2020-04-17  139.213139         NaN          NaN  0.000000
 3   2020-04-24  139.213139         NaN          NaN  0.000000
 4   2020-05-01  139.213139         NaN          NaN  0.000000
 ..         ...         ...         ...          ...       ...
 262 2025-04-11  114.540000      114.54   73491.5517  0.073880
 263 2025-04-18  112.700000      112.70   72310.9645 -0.016064
 264 2025-04-25  122.510000      122.51   78605.2907  0.087045
 265 2025-05-02  125.260000      125.26   78644.0632  0.022447
 266 2025-05-09  127.040000      127.04   79761.6302  0.014210

 [267 rows x 5 columns],
 'AAPL UW Equity':          Dates  PX_LAST  LAST_PRICE   CUR_MKT_CAP   returns
 0   2020-04-03   60.353      60.353  1.056285e+06       NaN
 1   2020-04-10   66.998      66.998  1.172585e+06  0.110102
 2   2020-04-17   70.700      70.700  1.237386e+06  0.055255
 3   2020-04-24   70.743      70.743  1.238130e+06  0.000608
 4   2020-05-01   72.268      72.268  1.252926e+06  0.021557
 ..         ...      ...         ...           ...       ...
 262 2025-04-11  198.150     198.150  2.976624e+06  0.051863
 263 2025-04-18  196.980     196.980  2.959048e+06 -0.005905
 264 2025-04-25  209.280     209.280  3.143819e+06  0.062443
 265 2025-05-02  205.350     205.350  3.067072e+06 -0.018779
 266 2025-05-09  198.530     198.530  2.965210e+06 -0.033212

 [267 rows x 5 columns],
 'ADI UW Equity':          Dates  PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03    86.56       86.56   31873.1311       NaN
 1   2020-04-10    98.79       98.79   36376.4628  0.141289
 2   2020-04-17   102.80      102.80   37853.0254  0.040591
 3   2020-04-24   105.92      105.92   39001.8720  0.030350
 4   2020-05-01   103.64      103.64   38162.3302 -0.021526
 ..         ...      ...         ...          ...       ...
 262 2025-04-11   179.16      179.16   88859.1467  0.088457
 263 2025-04-18   176.27      176.27   87425.7747 -0.016131
 264 2025-04-25   194.59      194.59   96512.0638  0.103931
 265 2025-05-02   198.59      198.59   98495.9698  0.020556
 266 2025-05-09   207.51      207.51  102920.0800  0.044917

 [267 rows x 5 columns],
 'ADP UW Equity':          Dates  PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03   128.57      128.57   55510.6442       NaN
 1   2020-04-10   142.52      142.52   61533.6160  0.108501
 2   2020-04-17   141.08      141.08   60911.8899 -0.010104
 3   2020-04-24   139.23      139.23   60113.1445 -0.013113
 4   2020-05-01   140.42      140.42   60348.9179  0.008547
 ..         ...      ...         ...          ...       ...
 262 2025-04-11   299.54      299.54  121874.1073  0.046867
 263 2025-04-18   293.28      293.28  119327.0955 -0.020899
 264 2025-04-25   291.76      291.76  118708.6517 -0.005183
 265 2025-05-02   303.57      303.57  123225.9689  0.040478
 266 2025-05-09   307.72      307.72  124910.5483  0.013671

 [267 rows x 5 columns],
 'ADSK UW Equity':          Dates  PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03   139.00      139.00   30513.4781       NaN
 1   2020-04-10   164.90      164.90   36199.0830  0.186331
 2   2020-04-17   180.94      180.94   39720.2066  0.097271
 3   2020-04-24   180.35      180.35   39590.6890 -0.003261
 4   2020-05-01   174.90      174.90   38394.2972 -0.030219
 ..         ...      ...         ...          ...       ...
 262 2025-04-11   258.45      258.45   55049.8500  0.052707
 263 2025-04-18   259.47      259.47   55267.1100  0.003947
 264 2025-04-25   269.93      269.93   57495.0900  0.040313
 265 2025-05-02   279.99      279.99   59637.8700  0.037269
 266 2025-05-09   287.48      287.48   61504.7749  0.026751

 [267 rows x 5 columns],
 'AEP UW Equity':          Dates     PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03   89.845145         NaN          NaN       NaN
 1   2020-04-10   89.845145         NaN          NaN  0.000000
 2   2020-04-17   89.845145         NaN          NaN  0.000000
 3   2020-04-24   89.845145         NaN          NaN  0.000000
 4   2020-05-01   89.845145         NaN          NaN  0.000000
 ..         ...         ...         ...          ...       ...
 262 2025-04-11  104.630000      104.63   55871.1321  0.001436
 263 2025-04-18  107.710000      107.71   57515.8142  0.029437
 264 2025-04-25  106.740000      106.74   56997.8461 -0.009006
 265 2025-05-02  107.690000      107.69   57505.1344  0.008900
 266 2025-05-09  104.680000      104.68   55919.5353 -0.027951

 [267 rows x 5 columns],
 'AMAT UW Equity':          Dates  PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03    42.28       42.28   38825.9402       NaN
 1   2020-04-10    49.59       49.59   45538.7506  0.172895
 2   2020-04-17    53.20       53.20   48853.8321  0.072797
 3   2020-04-24    51.74       51.74   47513.1066 -0.027444
 4   2020-05-01    46.89       46.89   43059.3268 -0.093738
 ..         ...      ...         ...          ...       ...
 262 2025-04-11   144.94      144.94  117755.1767  0.141709
 263 2025-04-18   137.46      137.46  111678.1191 -0.051608
 264 2025-04-25   151.55      151.55  123125.4107  0.102503
 265 2025-05-02   155.10      155.10  126009.5757  0.023425
 266 2025-05-09   155.61      155.61  126423.9205  0.003288

 [267 rows x 5 columns],
 'AMGN UW Equity':          Dates  PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03   205.41      205.41  121152.2187       NaN
 1   2020-04-10   218.21      218.21  128255.6636  0.062314
 2   2020-04-17   234.97      234.97  138106.5638  0.076807
 3   2020-04-24   236.28      236.28  138876.5327  0.005575
 4   2020-05-01   230.98      230.98  135873.3842 -0.022431
 ..         ...      ...         ...          ...       ...
 262 2025-04-11   285.98      285.98  153757.3255 -0.028568
 263 2025-04-18   277.29      277.29  149085.1415 -0.030387
 264 2025-04-25   280.84      280.84  150993.8012  0.012802
 265 2025-05-02   281.22      281.22  151213.7145  0.001353
 266 2025-05-09   265.86      265.86  142954.5485 -0.054619

 [267 rows x 5 columns],
 'AMZN UW Equity':          Dates  PX_LAST  LAST_PRICE   CUR_MKT_CAP   returns
 0   2020-04-03   95.330      95.330  9.492075e+05       NaN
 1   2020-04-10  102.138     102.138  1.017001e+06  0.071415
 2   2020-04-17  118.750     118.750  1.183997e+06  0.162643
 3   2020-04-24  120.511     120.511  1.201555e+06  0.014829
 4   2020-05-01  114.302     114.302  1.140222e+06 -0.051522
 ..         ...      ...         ...           ...       ...
 262 2025-04-11  184.870     184.870  1.961908e+06  0.081111
 263 2025-04-18  172.610     172.610  1.831800e+06 -0.066317
 264 2025-04-25  188.990     188.990  2.005631e+06  0.094896
 265 2025-05-02  189.980     189.980  2.016895e+06  0.005238
 266 2025-05-09  193.060     193.060  2.049593e+06  0.016212

 [267 rows x 5 columns],
 'ANSS UW Equity':          Dates  PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03   218.30      218.30   18682.1978       NaN
 1   2020-04-10   237.92      237.92   20361.2850  0.089876
 2   2020-04-17   263.90      263.90   22584.6633  0.109196
 3   2020-04-24   259.45      259.45   22203.8306 -0.016862
 4   2020-05-01   255.64      255.64   21877.7694 -0.014685
 ..         ...      ...         ...          ...       ...
 262 2025-04-11   296.31      296.31   25972.0992  0.032979
 263 2025-04-18   302.74      302.74   26535.7002  0.021700
 264 2025-04-25   320.68      320.68   28108.1731  0.059259
 265 2025-05-02   328.76      328.76   28903.3112  0.025196
 266 2025-05-09   333.74      333.74   29341.1336  0.015148

 [267 rows x 5 columns],
 'APP UW Equity':          Dates     PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03   88.024906         NaN          NaN       NaN
 1   2020-04-10   88.024906         NaN          NaN  0.000000
 2   2020-04-17   88.024906         NaN          NaN  0.000000
 3   2020-04-24   88.024906         NaN          NaN  0.000000
 4   2020-05-01   88.024906         NaN          NaN  0.000000
 ..         ...         ...         ...          ...       ...
 262 2025-04-11  249.950000      249.95   84972.5598  0.139399
 263 2025-04-18  238.220000      238.22   80984.8498 -0.046929
 264 2025-04-25  276.830000      276.83   93668.9072  0.162077
 265 2025-05-02  307.580000      307.58  104073.5559  0.111079
 266 2025-05-09  328.540000      328.54  111173.6190  0.068145

 [267 rows x 5 columns],
 'ASML UW Equity':          Dates  PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03   244.61      244.61  104120.6202       NaN
 1   2020-04-10   276.81      276.81  117826.8627  0.131638
 2   2020-04-17   295.65      295.65  125846.2915  0.068061
 3   2020-04-24   291.84      291.84  124224.5280 -0.012887
 4   2020-05-01   279.06      279.06  118784.5970 -0.043791
 ..         ...      ...         ...          ...       ...
 262 2025-04-11   668.81      668.81  263397.9051  0.104467
 263 2025-04-18   640.16      640.16  252114.6558 -0.042837
 264 2025-04-25   677.27      677.27  266729.7128  0.057970
 265 2025-05-02   690.33      690.33  271873.1416  0.019283
 266 2025-05-09   706.21      706.21  278127.1730  0.023003

 [267 rows x 5 columns],
 'AVGO UW Equity':          Dates  PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03   23.426      23.426   93655.1205       NaN
 1   2020-04-10   25.430      25.430  101666.9390  0.085546
 2   2020-04-17   26.588      26.588  106296.5228  0.045537
 3   2020-04-24   26.481      26.481  105868.7461 -0.004024
 4   2020-05-01   25.970      25.970  103825.8123 -0.019297
 ..         ...      ...         ...          ...       ...
 262 2025-04-11  181.940     181.940  855472.5496  0.243694
 263 2025-04-18  170.990     170.990  803986.2111 -0.060185
 264 2025-04-25  192.310     192.310  904231.7578  0.124686
 265 2025-05-02  203.640     203.640  957504.8367  0.058915
 266 2025-05-09  208.200     208.200  978945.7229  0.022392

 [267 rows x 5 columns],
 'AXON UW Equity':          Dates  PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03    61.51       61.51    3679.0218       NaN
 1   2020-04-10    74.70       74.70    4467.9391  0.214437
 2   2020-04-17    76.72       76.72    4589.7173  0.027041
 3   2020-04-24    71.84       71.84    4297.7749 -0.063608
 4   2020-05-01    69.52       69.52    4158.9826 -0.032294
 ..         ...      ...         ...          ...       ...
 262 2025-04-11   567.98      567.98   43520.4826  0.142518
 263 2025-04-18   559.53      559.53   43558.3743 -0.014877
 264 2025-04-25   603.78      603.78   47003.1548  0.079084
 265 2025-05-02   628.16      628.16   48901.0926  0.040379
 266 2025-05-09   684.59      684.59   53295.8874  0.089834

 [267 rows x 5 columns],
 'AZN UW Equity':          Dates   PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03  64.83095         NaN          NaN       NaN
 1   2020-04-10  64.83095         NaN          NaN  0.000000
 2   2020-04-17  64.83095         NaN          NaN  0.000000
 3   2020-04-24  64.83095         NaN          NaN  0.000000
 4   2020-05-01  64.83095         NaN          NaN  0.000000
 ..         ...       ...         ...          ...       ...
 262 2025-04-11  66.29000       66.29  205583.4024 -0.031697
 263 2025-04-18  67.59000       67.59  209615.0576  0.019611
 264 2025-04-25  69.57000       69.57  215755.5786  0.029294
 265 2025-05-02  72.44000       72.44  224656.4989  0.041253
 266 2025-05-09  67.57000       67.57  209553.2804 -0.067228

 [267 rows x 5 columns],
 'BIIB UW Equity':          Dates  PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03   300.51      300.51   52307.9759       NaN
 1   2020-04-10   321.05      321.05   55883.2507  0.068350
 2   2020-04-17   342.55      342.55   59625.6270  0.066968
 3   2020-04-24   297.80      297.80   48597.2333 -0.130638
 4   2020-05-01   293.09      293.09   47828.6203 -0.015816
 ..         ...      ...         ...          ...       ...
 262 2025-04-11   115.17      115.17   16858.0015 -0.063506
 263 2025-04-18   118.61      118.61   17361.5313  0.029869
 264 2025-04-25   118.84      118.84   17395.1975  0.001939
 265 2025-05-02   123.53      123.53   18100.5831  0.039465
 266 2025-05-09   118.17      118.17   17315.1939 -0.043390

 [267 rows x 5 columns],
 'BKNG UW Equity':          Dates  PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03  1230.68     1230.68   50533.9533       NaN
 1   2020-04-10  1420.64     1420.64   58334.0554  0.154354
 2   2020-04-17  1470.87     1470.87   60396.5904  0.035357
 3   2020-04-24  1362.77     1362.77   55778.4514 -0.073494
 4   2020-05-01  1448.79     1448.79   59299.2674  0.063121
 ..         ...      ...         ...          ...       ...
 262 2025-04-11  4586.53     4586.53  150507.9038  0.070614
 263 2025-04-18  4573.31     4573.31  150074.0869 -0.002882
 264 2025-04-25  4838.44     4838.44  158212.8027  0.057973
 265 2025-05-02  5202.80     5202.80  169300.8705  0.075305
 266 2025-05-09  5072.54     5072.54  165062.1661 -0.025037

 [267 rows x 5 columns],
 'BKR UW Equity':          Dates    PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03  33.049302         NaN   10724.1555       NaN
 1   2020-04-10  33.049302         NaN   13260.8307  0.000000
 2   2020-04-17  33.049302         NaN   13436.1294  0.000000
 3   2020-04-24  33.049302         NaN   13855.6487  0.000000
 4   2020-05-01  33.049302         NaN   14144.7382  0.000000
 ..         ...        ...         ...          ...       ...
 262 2025-04-11  37.930000       37.93   37563.9596  0.071166
 263 2025-04-18  38.910000       38.91   38534.5022  0.025837
 264 2025-04-25  36.450000       36.45   36112.8366 -0.063223
 265 2025-05-02  37.100000       37.10   36756.8241  0.017833
 266 2025-05-09  36.490000       36.49   36152.4666 -0.016442

 [267 rows x 5 columns],
 'CCEP UW Equity':          Dates    PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03  63.566466         NaN          NaN       NaN
 1   2020-04-10  63.566466         NaN          NaN  0.000000
 2   2020-04-17  63.566466         NaN          NaN  0.000000
 3   2020-04-24  63.566466         NaN          NaN  0.000000
 4   2020-05-01  63.566466         NaN          NaN  0.000000
 ..         ...        ...         ...          ...       ...
 262 2025-04-11  86.600000       86.60   39862.3282  0.031812
 263 2025-04-18  89.310000       89.31   41109.7521  0.031293
 264 2025-04-25  87.880000       87.88   40451.5174 -0.016012
 265 2025-05-02  89.710000       89.71   41293.8737  0.020824
 266 2025-05-09  89.500000       89.50   41197.2099 -0.002341

 [267 rows x 5 columns],
 'CDNS UW Equity':          Dates  PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03    63.93       63.93   17953.6694       NaN
 1   2020-04-10    71.65       71.65   20121.7021  0.120757
 2   2020-04-17    78.65       78.65   22087.5348  0.097697
 3   2020-04-24    80.52       80.52   22480.1372  0.023776
 4   2020-05-01    75.84       75.84   21173.5421 -0.058122
 ..         ...      ...         ...          ...       ...
 262 2025-04-11   259.47      259.47   71176.1493  0.114179
 263 2025-04-18   260.22      260.22   71381.8845  0.002891
 264 2025-04-25   289.63      289.63   79449.4474  0.113020
 265 2025-05-02   308.15      308.15   84137.8923  0.063944
 266 2025-05-09   305.78      305.78   83490.7828 -0.007691

 [267 rows x 5 columns],
 'CDW UW Equity':          Dates  PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03    86.89       86.89   12405.4190       NaN
 1   2020-04-10   106.26      106.26   15170.9037  0.222926
 2   2020-04-17   108.82      108.82   15480.4891  0.024092
 3   2020-04-24   104.77      104.77   14904.3452 -0.037217
 4   2020-05-01   106.82      106.82   15195.9736  0.019567
 ..         ...      ...         ...          ...       ...
 262 2025-04-11   148.80      148.80   19606.8867  0.029829
 263 2025-04-18   151.47      151.47   19958.7039  0.017944
 264 2025-04-25   157.95      157.95   20812.5522  0.042781
 265 2025-05-02   166.83      166.83   21982.6406  0.056220
 266 2025-05-09   178.94      178.94   23563.7407  0.072589

 [267 rows x 5 columns],
 'CEG UW Equity':          Dates     PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03  137.173439         NaN          NaN       NaN
 1   2020-04-10  137.173439         NaN          NaN  0.000000
 2   2020-04-17  137.173439         NaN          NaN  0.000000
 3   2020-04-24  137.173439         NaN          NaN  0.000000
 4   2020-05-01  137.173439         NaN          NaN  0.000000
 ..         ...         ...         ...          ...       ...
 262 2025-04-11  208.250000      208.25   65623.9355  0.218121
 263 2025-04-18  206.680000      206.68   65129.1957 -0.007539
 264 2025-04-25  222.990000      222.99   70268.8182  0.078914
 265 2025-05-02  247.260000      247.26   77916.8034  0.108839
 266 2025-05-09  271.370000      271.37   85514.3692  0.097509

 [267 rows x 5 columns],
 'CHTR UW Equity':          Dates  PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03   433.80      433.80  100773.6201       NaN
 1   2020-04-10   466.64      466.64  108402.4944  0.075703
 2   2020-04-17   499.42      499.42  116017.4305  0.070247
 3   2020-04-24   508.55      508.55  118138.3691  0.018281
 4   2020-05-01   509.64      509.64  116598.4517  0.002143
 ..         ...      ...         ...          ...       ...
 262 2025-04-11   334.38      334.38   52994.4092 -0.011558
 263 2025-04-18   338.96      338.96   53720.2732  0.013697
 264 2025-04-25   373.65      373.65   58601.6320  0.102342
 265 2025-05-02   385.00      385.00   60381.7164  0.030376
 266 2025-05-09   401.73      401.73   63005.5764  0.043455

 [267 rows x 5 columns],
 'CMCSA UW Equity':          Dates  PX_LAST  LAST_PRICE  CUR_MKT_CAP   returns
 0   2020-04-03    33.95       33.95  154575.5262       NaN
 1   2020-04-10    38.00       38.00  173015.3165  0.119293
 2   2020-04-17    38.08       38.08  173379.5593  0.002105
 3   2020-04-24    37.16       37.16  169604.0971 -0.024160
 4   2020-05-01    36.98       36.98  168782.5487 -0.004844
 ..         ...      ...         ...          ...       ...
 262 2025-04-11    33.72       33.72  127496.0821  0.010186
 263 2025-04-18    34.01       34.01  128592.5787  0.008600
 264 2025-04-25    33.90       33.90  126572.5631 -0.003234
 265 2025-05-02    34.46       34.46  128663.4373  0.016519

In [ ]:
import pandas as pd

# # Sample dictionary of DataFrames (replace with your actual 100 DataFrames)
# ticker_data = {
#     'AAPL': pd.DataFrame({'Dates': pd.date_range('2023-01-01', periods=5), 'Returns': [0.01, 0.02, 0.03, 0.04, 0.05]}),
#     'MSFT': pd.DataFrame({'Dates': pd.date_range('2023-01-01', periods=5), 'Returns': [0.02, 0.01, 0.04, 0.03, 0.05]}),
#     'GOOGL': pd.DataFrame({'Dates': pd.date_range('2023-01-01', periods=5), 'Returns': [0.03, 0.02, 0.01, 0.05, 0.04]})
# }

# Initialize an empty list to collect individual DataFrames
returns_list = []

# Loop through each ticker and prepare the DataFrame for merging
for ticker, df in ticker_data.items():
    # Ensure Dates column is set as index for proper alignment
    df = df.set_index('Dates')[['returns']]
    df.columns = [ticker]  # Rename the column to the ticker name
    returns_list.append(df)

# Concatenating all ticker DataFrames along the columns (aligning by Dates)
returns_df = pd.concat(returns_list, axis=1)

# Displaying the final returns DataFrame
returns_df.head()  # Displaying the first few rows of the combined DataFrame.

,ADBE UW Equity,AMD UW Equity,ABNB UW Equity,AAPL UW Equity,ADI UW Equity,ADP UW Equity,ADSK UW Equity,AEP UW Equity,AMAT UW Equity,AMGN UW Equity,...,TSLA UW Equity,TTD UQ Equity,TTWO UW Equity,TXN UW Equity,VRSK UW Equity,VRTX UW Equity,WBD UW Equity,WDAY UW Equity,XEL UW Equity,ZS UW Equity
Dates,,,,,,,,,,,,,,,,,,,,,
2020-04-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-04-10,0.085453,0.135947,0.0,0.110102,0.141289,0.108501,0.186331,0.0,0.172895,0.062314,...,0.193724,0.332751,0.007680,0.077115,0.046664,0.034829,0.0,0.252671,0.145351,-0.012776
2020-04-17,0.079730,0.169905,0.0,0.055255,0.040591,-0.010104,0.097271,0.0,0.072797,0.076807,...,0.315688,0.069049,0.042211,0.054415,0.037299,0.096711,0.0,0.026752,0.013279,0.086436
2020-04-24,-0.000029,-0.007420,0.0,0.000608,0.030350,-0.013113,-0.003261,0.0,-0.027444,0.005575,...,-0.038122,0.123009,0.027644,0.003347,-0.034137,-0.002218,0.0,-0.029069,-0.038421,-0.007353
2020-05-01,-0.000756,-0.112140,0.0,0.021557,-0.021526,0.008547,-0.030219,0.0,-0.093738,-0.022431,...,-0.032861,0.086779,-0.040898,-0.037040,0.033055,-0.055436,0.0,0.011727,-0.037014,-0.009630

In [ ]:
# returns_df.index = returns_df.index.strftime('%Y-%m-%d')
# returns_df.to_excel("returns_equities.xlsx", index=True)

In [ ]:
# correlation_matrix = returns_df.iloc[:186].corr()   ## 1ST INSTANCE
# correlation_matrix = returns_df.iloc[20:206].corr()   ## 2ND INSTANCE
# correlation_matrix = returns_df.iloc[40:226].corr()  ## 3RD INSTANCE
correlation_matrix = returns_df.iloc[60:246].corr()

In [ ]:
correlation_matrix.columns = [col.split(' UW Equity')[0].split(' UQ Equity')[0] for col in correlation_matrix.columns]
correlation_matrix.index = [idx.split(' UW Equity')[0].split(' UQ Equity')[0] for idx in correlation_matrix.index]

In [ ]:
correlation_matrix.head()

,ADBE,AMD,ABNB,AAPL,ADI,ADP,ADSK,AEP,AMAT,AMGN,...,TSLA,TTD,TTWO,TXN,VRSK,VRTX,WBD,WDAY,XEL,ZS
ADBE,1.000000,0.476796,0.371187,0.564165,0.445033,0.406864,0.595166,0.101644,0.496981,0.211095,...,0.295846,0.380129,0.262950,0.436196,0.490642,0.138278,0.039584,0.583310,0.104782,0.495099
AMD,0.476796,1.000000,0.364638,0.425575,0.570908,0.357830,0.494818,0.021309,0.708608,0.066539,...,0.403286,0.379564,0.269764,0.557763,0.250137,0.125390,0.056289,0.367162,-0.043992,0.433356
ABNB,0.371187,0.364638,1.000000,0.395825,0.523078,0.344349,0.493066,0.022567,0.450201,0.060581,...,0.432336,0.469551,0.269457,0.402685,0.362536,0.133639,0.169946,0.421150,-0.066016,0.457014
AAPL,0.564165,0.425575,0.395825,1.000000,0.505581,0.437808,0.550989,0.197559,0.525975,0.203050,...,0.491367,0.334083,0.230437,0.482561,0.540205,0.316693,0.081784,0.467356,0.201052,0.504188
ADI,0.445033,0.570908,0.523078,0.505581,1.000000,0.416436,0.599043,0.099309,0.720160,0.123553,...,0.370584,0.434040,0.265247,0.791705,0.421257,0.272429,0.092157,0.343322,0.032504,0.453266

In [ ]:
correlation_matrix.to_excel("correlation_matrix4.xlsx", index=True)

In [ ]:
correlation_matrix.shape

(97, 97)

In [ ]:
final_returns_df =returns_df.copy()

In [ ]:
fnal_returns_df.columns = [col.split(' UW Equity')[0].split(' UQ Equity')[0] for col in fnal_returns_df.columns]

In [ ]:
fnal_returns_df

,ADBE,AMD,ABNB,AAPL,ADI,ADP,ADSK,AEP,AMAT,AMGN,...,TSLA,TTD,TTWO,TXN,VRSK,VRTX,WBD,WDAY,XEL,ZS
Dates,,,,,,,,,,,,,,,,,,,,,
2020-04-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-04-10,0.085453,0.135947,0.000000,0.110102,0.141289,0.108501,0.186331,0.000000,0.172895,0.062314,...,0.193724,0.332751,0.007680,0.077115,0.046664,0.034829,0.000000,0.252671,0.145351,-0.012776
2020-04-17,0.079730,0.169905,0.000000,0.055255,0.040591,-0.010104,0.097271,0.000000,0.072797,0.076807,...,0.315688,0.069049,0.042211,0.054415,0.037299,0.096711,0.000000,0.026752,0.013279,0.086436
2020-04-24,-0.000029,-0.007420,0.000000,0.000608,0.030350,-0.013113,-0.003261,0.000000,-0.027444,0.005575,...,-0.038122,0.123009,0.027644,0.003347,-0.034137,-0.002218,0.000000,-0.029069,-0.038421,-0.007353
2020-05-01,-0.000756,-0.112140,0.000000,0.021557,-0.021526,0.008547,-0.030219,0.000000,-0.093738,-0.022431,...,-0.032861,0.086779,-0.040898,-0.037040,0.033055,-0.055436,0.000000,0.011727,-0.037014,-0.009630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-11,0.009740,0.089086,0.073880,0.051863,0.088457,0.046867,0.052707,0.001436,0.141709,-0.028568,...,0.053794,0.076557,0.089886,-0.025035,0.024176,0.020227,-0.012392,0.043152,0.024525,0.134024
2025-04-18,-0.010412,-0.063169,-0.016064,-0.005905,-0.016131,-0.020899,0.003947,0.029437,-0.051608,-0.030387,...,-0.043359,0.009642,0.003301,0.005691,0.003906,0.010078,0.017566,-0.024237,0.008267,0.015196
2025-04-25,0.054243,0.104514,0.087045,0.062443,0.103931,-0.005183,0.040313,-0.009006,0.102503,0.012802,...,0.180553,0.073816,0.059266,0.097144,-0.023787,0.009691,0.059186,0.083748,-0.016113,0.072057
2025-05-02,0.035761,0.022298,0.022447,-0.018779,0.020556,0.040478,0.037269,0.008900,0.023425,0.001353,...,0.007931,0.002223,-0.026089,0.010131,0.027443,0.014802,-0.005821,0.038200,0.025652,0.069069
2025-05-09,0.006328,0.040891,0.014210,-0.033212,0.044917,0.013671,0.026751,-0.027951,0.003288,-0.054619,...,0.038474,0.313367,0.032118,0.047170,0.053079,-0.151970,0.062061,0.042223,-0.002261,0.011238

In [ ]:
fnal_returns_df.index = pd.to_datetime(fnal_returns_df.index, errors='coerce')

# Now you can use strftime() without any error
fnal_returns_df.index = fnal_returns_df.index.strftime('%Y-%m-%d')

# Save the DataFrame to Excel
fnal_returns_df.to_excel("returns_equities.xlsx", index=True)

In [ ]:
fnal_returns_df

,ADBE,AMD,ABNB,AAPL,ADI,ADP,ADSK,AEP,AMAT,AMGN,...,TSLA,TTD,TTWO,TXN,VRSK,VRTX,WBD,WDAY,XEL,ZS
Dates,,,,,,,,,,,,,,,,,,,,,
2020-04-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-04-10,0.085453,0.135947,0.000000,0.110102,0.141289,0.108501,0.186331,0.000000,0.172895,0.062314,...,0.193724,0.332751,0.007680,0.077115,0.046664,0.034829,0.000000,0.252671,0.145351,-0.012776
2020-04-17,0.079730,0.169905,0.000000,0.055255,0.040591,-0.010104,0.097271,0.000000,0.072797,0.076807,...,0.315688,0.069049,0.042211,0.054415,0.037299,0.096711,0.000000,0.026752,0.013279,0.086436
2020-04-24,-0.000029,-0.007420,0.000000,0.000608,0.030350,-0.013113,-0.003261,0.000000,-0.027444,0.005575,...,-0.038122,0.123009,0.027644,0.003347,-0.034137,-0.002218,0.000000,-0.029069,-0.038421,-0.007353
2020-05-01,-0.000756,-0.112140,0.000000,0.021557,-0.021526,0.008547,-0.030219,0.000000,-0.093738,-0.022431,...,-0.032861,0.086779,-0.040898,-0.037040,0.033055,-0.055436,0.000000,0.011727,-0.037014,-0.009630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-11,0.009740,0.089086,0.073880,0.051863,0.088457,0.046867,0.052707,0.001436,0.141709,-0.028568,...,0.053794,0.076557,0.089886,-0.025035,0.024176,0.020227,-0.012392,0.043152,0.024525,0.134024
2025-04-18,-0.010412,-0.063169,-0.016064,-0.005905,-0.016131,-0.020899,0.003947,0.029437,-0.051608,-0.030387,...,-0.043359,0.009642,0.003301,0.005691,0.003906,0.010078,0.017566,-0.024237,0.008267,0.015196
2025-04-25,0.054243,0.104514,0.087045,0.062443,0.103931,-0.005183,0.040313,-0.009006,0.102503,0.012802,...,0.180553,0.073816,0.059266,0.097144,-0.023787,0.009691,0.059186,0.083748,-0.016113,0.072057
2025-05-02,0.035761,0.022298,0.022447,-0.018779,0.020556,0.040478,0.037269,0.008900,0.023425,0.001353,...,0.007931,0.002223,-0.026089,0.010131,0.027443,0.014802,-0.005821,0.038200,0.025652,0.069069
2025-05-09,0.006328,0.040891,0.014210,-0.033212,0.044917,0.013671,0.026751,-0.027951,0.003288,-0.054619,...,0.038474,0.313367,0.032118,0.047170,0.053079,-0.151970,0.062061,0.042223,-0.002261,0.011238