In [ ]:
# Creating two separate lists: one for tickers and one for their percentages
tickers = [
    "ADBE", "AMD", "ABNB", "GOOG", "GOOGL", "AMZN", "AEP", "AMGN", "ADI",
    "ANSS", "AAPL", "AMAT", "APP", "ASML", "AZN", "TEAM", "ADSK", "ADP",
    "AXON", "BKR", "BIIB", "BKNG", "AVGO", "CDNS", "CDW", "CHTR", "CTAS",
    "CSCO", "CCEP", "CTSH", "CMCSA", "CEG", "CPRT", "CSGP", "COST", "CRWD",
    "CSX", "DDOG", "DXCM", "FANG", "EA", "EXC", "FAST", "FTNT", "GEHC",
    "GILD", "GFS", "HON", "IDXX", "INTC", "INTU", "ISRG", "KDP", "KLAC",
    "KHC", "LRCX", "LULU", "MAR", "MRVL", "MELI", "META", "MCHP", "MU",
    "MSFT", "MSTR", "MDLZ", "MDB", "MNST", "NFLX", "NVDA", "NXPI", "ORLY",
    "ODFL", "ON", "PCAR", "PANW", "PAYX", "PYPL", "PDD", "PEP", "QCOM",
    "REGN", "ROP", "ROST", "SBUX", "SNPS", "TMUS", "TTWO", "TSLA", "TXN",
    "TTD", "VRSK", "VRTX", "WBD", "WDAY", "XEL", "ZS"
]

percentages = [
    0.01304679819, 0.007444836888, 0.004005177201, 0.08536828073, 0.08536828073,
    0.08596606561, 0.002252240544, 0.008261548247, 0.004315753899, 0.001638495237,
    0.1386899174, 0.005674919243, 0.0006140451507, 0.01417822079, 0.009099394815,
    0.003409253043, 0.003148990536, 0.005155827134, 0.0005894598392, 0.001527641345,
    0.002518652367, 0.005225460367, 0.01254849386, 0.002532459839, 0.001366813626,
    0.006562017268, 0.002391424225, 0.01243783895, 0.0008238376198, 0.002241413637,
    0.01231033781, 0.0007020154808, 0.001792315944, 0.001881895376, 0.01190570651,
    0.002285441592, 0.004082212706, 0.001879215292, 0.002485932903, 0.001042582766,
    0.002262338015, 0.002592999663, 0.001775767591, 0.002330500752, 0.0003772729843,
    0.005462116271, 0.0009851712065, 0.005255415554, 0.002379946685, 0.01164038601,
    0.007013683757, 0.005614255154, 0.002463849088, 0.002879605302, 0.002746306882,
    0.00417080725, 0.002654332989, 0.002784831533, 0.002375312222, 0.00362340655,
    0.04090321438, 0.002264535482, 0.004441971514, 0.1177834758, 0.0002256897532,
    0.005285658773, 0.0011658912, 0.002924427462, 0.01142807504, 0.02835605467,
    0.002765987387, 0.002564825437, 0.001831529244, 0.001312224582, 0.001953574769,
    0.001694029799, 0.002310732418, 0.0110643137, 0.00660689107, 0.01347919551,
    0.008829664527, 0.004190770016, 0.0001181116457, 0.002237720661, 0.006835154016,
    0.00271136567, 0.009754355759, 0.001190223903, 0.03817994959, 0.009308311265,
    0.001794759498, 0.001837852118, 0.004180028306, 0.001515644868, 0.003130759339,
    0.00224257674, 0.00142093396
]

tickers[:5], percentages[:5]  # Displaying the first 5 values to ensure correctness.

(['ADBE', 'AMD', 'ABNB', 'GOOG', 'GOOGL'],
 [0.01304679819, 0.007444836888, 0.004005177201, 0.08536828073, 0.08536828073])

In [ ]:
# Calculating the sum of all percentages to check if they sum to 1 (or close)
total_percentage = sum(percentages)
total_percentage

1.0000000000411997

In [ ]:
formatted_string = ""

for ticker, percentage in zip(tickers, percentages):
    formatted_string += f"{ticker}  {percentage:.11f}    "

# Removing the extra spaces at the end
formatted_string = formatted_string.strip()

# Displaying the final formatted string
formatted_string

'ADBE  0.01304679819    AMD  0.00744483689    ABNB  0.00400517720    GOOG  0.08536828073    GOOGL  0.08536828073    AMZN  0.08596606561    AEP  0.00225224054    AMGN  0.00826154825    ADI  0.00431575390    ANSS  0.00163849524    AAPL  0.13868991740    AMAT  0.00567491924    APP  0.00061404515    ASML  0.01417822079    AZN  0.00909939482    TEAM  0.00340925304    ADSK  0.00314899054    ADP  0.00515582713    AXON  0.00058945984    BKR  0.00152764135    BIIB  0.00251865237    BKNG  0.00522546037    AVGO  0.01254849386    CDNS  0.00253245984    CDW  0.00136681363    CHTR  0.00656201727    CTAS  0.00239142423    CSCO  0.01243783895    CCEP  0.00082383762    CTSH  0.00224141364    CMCSA  0.01231033781    CEG  0.00070201548    CPRT  0.00179231594    CSGP  0.00188189538    COST  0.01190570651    CRWD  0.00228544159    CSX  0.00408221271    DDOG  0.00187921529    DXCM  0.00248593290    FANG  0.00104258277    EA  0.00226233801    EXC  0.00259299966    FAST  0.00177576759    FTNT  0.00233050075    GEHC  0.00037727298    GILD  0.00546211627    GFS  0.00098517121    HON  0.00525541555    IDXX  0.00237994668    INTC  0.01164038601    INTU  0.00701368376    ISRG  0.00561425515    KDP  0.00246384909    KLAC  0.00287960530    KHC  0.00274630688    LRCX  0.00417080725    LULU  0.00265433299    MAR  0.00278483153    MRVL  0.00237531222    MELI  0.00362340655    META  0.04090321438    MCHP  0.00226453548    MU  0.00444197151    MSFT  0.11778347580    MSTR  0.00022568975    MDLZ  0.00528565877    MDB  0.00116589120    MNST  0.00292442746    NFLX  0.01142807504    NVDA  0.02835605467    NXPI  0.00276598739    ORLY  0.00256482544    ODFL  0.00183152924    ON  0.00131222458    PCAR  0.00195357477    PANW  0.00169402980    PAYX  0.00231073242    PYPL  0.01106431370    PDD  0.00660689107    PEP  0.01347919551    QCOM  0.00882966453    REGN  0.00419077002    ROP  0.00011811165    ROST  0.00223772066    SBUX  0.00683515402    SNPS  0.00271136567    TMUS  0.00975435576    TTWO  0.00119022390    TSLA  0.03817994959    TXN  0.00930831127    TTD  0.00179475950    VRSK  0.00183785212    VRTX  0.00418002831    WBD  0.00151564487    WDAY  0.00313075934    XEL  0.00224257674    ZS  0.00142093396'

In [ ]:
cleaned_tickers = ['ADBE', 'AMD', 'ABNB', 'GOOG', 'GOOGL', 'AMZN', 'AEP', 'AMGN', 'ADI', 'ANSS', 'AAPL', 'AMAT', 'APP', 'ASML', 'AZN', 'TEAM', 'ADSK', 'ADP', 'AXON', 'BKR', 'BIIB', 'BKNG', 'AVGO', 'CDNS', 'CDW', 'CHTR', 'CTAS', 'CSCO', 'CCEP', 'CTSH', 'CMCSA', 'CEG', 'CPRT', 'CSGP', 'COST', 'CRWD', 'CSX', 'DDOG', 'DXCM', 'FANG', 'EA', 'EXC', 'FAST', 'FTNT', 'GEHC', 'GILD', 'GFS', 'HON', 'IDXX', 'INTC', 'INTU', 'ISRG', 'KDP', 'KLAC', 'KHC', 'LRCX', 'LULU', 'MAR', 'MRVL', 'MELI', 'META', 'MCHP', 'MU', 'MSFT', 'MSTR', 'MDLZ', 'MDB', 'MNST', 'NFLX', 'NVDA', 'NXPI', 'ORLY', 'ODFL', 'ON', 'PCAR', 'PANW', 'PAYX', 'PYPL', 'PDD', 'PEP', 'QCOM', 'REGN', 'ROP', 'ROST', 'SBUX', 'SNPS', 'TMUS', 'TTWO', 'TSLA', 'TXN', 'TTD', 'VRSK', 'VRTX', 'WBD', 'WDAY', 'XEL', 'ZS']

In [ ]:
ticker_pairs = formatted_string.split("    ")  # Splitting by 4 spaces

# Filtering only those pairs where the ticker is in the final list
filtered_pairs = [pair for pair in ticker_pairs if pair.split()[0] in cleaned_tickers]

# Reconstructing the filtered string
filtered_string = "    ".join(filtered_pairs)

# Displaying the final filtered string
filtered_string

'ADBE  0.01304679819    AMD  0.00744483689    ABNB  0.00400517720    GOOG  0.08536828073    GOOGL  0.08536828073    AMZN  0.08596606561    AEP  0.00225224054    AMGN  0.00826154825    ADI  0.00431575390    ANSS  0.00163849524    AAPL  0.13868991740    AMAT  0.00567491924    APP  0.00061404515    ASML  0.01417822079    AZN  0.00909939482    TEAM  0.00340925304    ADSK  0.00314899054    ADP  0.00515582713    AXON  0.00058945984    BKR  0.00152764135    BIIB  0.00251865237    BKNG  0.00522546037    AVGO  0.01254849386    CDNS  0.00253245984    CDW  0.00136681363    CHTR  0.00656201727    CTAS  0.00239142423    CSCO  0.01243783895    CCEP  0.00082383762    CTSH  0.00224141364    CMCSA  0.01231033781    CEG  0.00070201548    CPRT  0.00179231594    CSGP  0.00188189538    COST  0.01190570651    CRWD  0.00228544159    CSX  0.00408221271    DDOG  0.00187921529    DXCM  0.00248593290    FANG  0.00104258277    EA  0.00226233801    EXC  0.00259299966    FAST  0.00177576759    FTNT  0.00233050075    GEHC  0.00037727298    GILD  0.00546211627    GFS  0.00098517121    HON  0.00525541555    IDXX  0.00237994668    INTC  0.01164038601    INTU  0.00701368376    ISRG  0.00561425515    KDP  0.00246384909    KLAC  0.00287960530    KHC  0.00274630688    LRCX  0.00417080725    LULU  0.00265433299    MAR  0.00278483153    MRVL  0.00237531222    MELI  0.00362340655    META  0.04090321438    MCHP  0.00226453548    MU  0.00444197151    MSFT  0.11778347580    MSTR  0.00022568975    MDLZ  0.00528565877    MDB  0.00116589120    MNST  0.00292442746    NFLX  0.01142807504    NVDA  0.02835605467    NXPI  0.00276598739    ORLY  0.00256482544    ODFL  0.00183152924    ON  0.00131222458    PCAR  0.00195357477    PANW  0.00169402980    PAYX  0.00231073242    PYPL  0.01106431370    PDD  0.00660689107    PEP  0.01347919551    QCOM  0.00882966453    REGN  0.00419077002    ROP  0.00011811165    ROST  0.00223772066    SBUX  0.00683515402    SNPS  0.00271136567    TMUS  0.00975435576    TTWO  0.00119022390    TSLA  0.03817994959    TXN  0.00930831127    TTD  0.00179475950    VRSK  0.00183785212    VRTX  0.00418002831    WBD  0.00151564487    WDAY  0.00313075934    XEL  0.00224257674    ZS  0.00142093396'

In [ ]:
desired_order =[
    "ADBE", "AMD", "ABNB", "AAPL", "ADI", "ADP", "ADSK", "AEP", "AMAT", "AMGN",
    "AMZN", "ANSS", "APP", "ASML", "AVGO", "AXON", "AZN", "BIIB", "BKNG", "BKR",
    "CCEP", "CDNS", "CDW", "CEG", "CHTR", "CMCSA", "COST", "CPRT", "CRWD", "CSCO",
    "CSGP", "CSX", "CTAS", "CTSH", "DDOG", "DXCM", "EA", "EXC", "FANG", "FAST",
    "FTNT", "GEHC", "GFS", "GILD", "GOOG", "GOOGL", "HON", "IDXX", "INTC", "INTU",
    "ISRG", "KDP", "KHC", "KLAC", "LRCX", "LULU", "MAR", "MCHP", "MDB", "MDLZ",
    "MELI", "META", "MNST", "MRVL", "MSFT", "MSTR", "MU", "NFLX", "NVDA", "NXPI",
    "ODFL", "ON", "ORLY", "PANW", "PAYX", "PCAR", "PDD", "PEP", "PYPL", "QCOM",
    "REGN", "ROP", "ROST", "SBUX", "SNPS", "TEAM", "TMUS", "TSLA", "TTD", "TTWO",
    "TXN", "VRSK", "VRTX", "WBD", "WDAY", "XEL", "ZS"
]

# Splitting the original formatted string into pairs (Ticker  Percentage)
ticker_pairs = formatted_string.split("    ")

# Creating a dictionary to map tickers to their percentage values
ticker_dict = {pair.split()[0]: pair for pair in ticker_pairs}

# Reordering the ticker pairs according to the desired order
ordered_string = "    ".join([ticker_dict[ticker] for ticker in desired_order if ticker in ticker_dict])

# Displaying the final ordered string
ordered_string

'ADBE  0.01304679819    AMD  0.00744483689    ABNB  0.00400517720    AAPL  0.13868991740    ADI  0.00431575390    ADP  0.00515582713    ADSK  0.00314899054    AEP  0.00225224054    AMAT  0.00567491924    AMGN  0.00826154825    AMZN  0.08596606561    ANSS  0.00163849524    APP  0.00061404515    ASML  0.01417822079    AVGO  0.01254849386    AXON  0.00058945984    AZN  0.00909939482    BIIB  0.00251865237    BKNG  0.00522546037    BKR  0.00152764135    CCEP  0.00082383762    CDNS  0.00253245984    CDW  0.00136681363    CEG  0.00070201548    CHTR  0.00656201727    CMCSA  0.01231033781    COST  0.01190570651    CPRT  0.00179231594    CRWD  0.00228544159    CSCO  0.01243783895    CSGP  0.00188189538    CSX  0.00408221271    CTAS  0.00239142423    CTSH  0.00224141364    DDOG  0.00187921529    DXCM  0.00248593290    EA  0.00226233801    EXC  0.00259299966    FANG  0.00104258277    FAST  0.00177576759    FTNT  0.00233050075    GEHC  0.00037727298    GFS  0.00098517121    GILD  0.00546211627    GOOG  0.08536828073    GOOGL  0.08536828073    HON  0.00525541555    IDXX  0.00237994668    INTC  0.01164038601    INTU  0.00701368376    ISRG  0.00561425515    KDP  0.00246384909    KHC  0.00274630688    KLAC  0.00287960530    LRCX  0.00417080725    LULU  0.00265433299    MAR  0.00278483153    MCHP  0.00226453548    MDB  0.00116589120    MDLZ  0.00528565877    MELI  0.00362340655    META  0.04090321438    MNST  0.00292442746    MRVL  0.00237531222    MSFT  0.11778347580    MSTR  0.00022568975    MU  0.00444197151    NFLX  0.01142807504    NVDA  0.02835605467    NXPI  0.00276598739    ODFL  0.00183152924    ON  0.00131222458    ORLY  0.00256482544    PANW  0.00169402980    PAYX  0.00231073242    PCAR  0.00195357477    PDD  0.00660689107    PEP  0.01347919551    PYPL  0.01106431370    QCOM  0.00882966453    REGN  0.00419077002    ROP  0.00011811165    ROST  0.00223772066    SBUX  0.00683515402    SNPS  0.00271136567    TEAM  0.00340925304    TMUS  0.00975435576    TSLA  0.03817994959    TTD  0.00179475950    TTWO  0.00119022390    TXN  0.00930831127    VRSK  0.00183785212    VRTX  0.00418002831    WBD  0.00151564487    WDAY  0.00313075934    XEL  0.00224257674    ZS  0.00142093396'

In [ ]:
import pandas as pd

# Re-defining the ticker-percentage string after reset
ticker_percentage_string = """
ADBE  0.01304679819    AMD  0.00744483689    ABNB  0.00400517720    AAPL  0.13868991740    ADI  0.00431575390    ADP  0.00515582713    ADSK  0.00314899054    AEP  0.00225224054    AMAT  0.00567491924    AMGN  0.00826154825    AMZN  0.08596606561    ANSS  0.00163849524    APP  0.00061404515    ASML  0.01417822079    AVGO  0.01254849386    AXON  0.00058945984    AZN  0.00909939482    BIIB  0.00251865237    BKNG  0.00522546037    BKR  0.00152764135    CCEP  0.00082383762    CDNS  0.00253245984    CDW  0.00136681363    CEG  0.00070201548    CHTR  0.00656201727    CMCSA  0.01231033781    COST  0.01190570651    CPRT  0.00179231594    CRWD  0.00228544159    CSCO  0.01243783895    CSGP  0.00188189538    CSX  0.00408221271    CTAS  0.00239142423    CTSH  0.00224141364    DDOG  0.00187921529    DXCM  0.00248593290    EA  0.00226233801    EXC  0.00259299966    FANG  0.00104258277    FAST  0.00177576759    FTNT  0.00233050075    GEHC  0.00037727298    GFS  0.00098517121    GILD  0.00546211627    GOOG  0.08536828073    GOOGL  0.08536828073    HON  0.00525541555    IDXX  0.00237994668    INTC  0.01164038601    INTU  0.00701368376    ISRG  0.00561425515    KDP  0.00246384909    KHC  0.00274630688    KLAC  0.00287960530    LRCX  0.00417080725    LULU  0.00265433299    MAR  0.00278483153    MCHP  0.00226453548    MDB  0.00116589120    MDLZ  0.00528565877    MELI  0.00362340655    META  0.04090321438    MNST  0.00292442746    MRVL  0.00237531222    MSFT  0.11778347580    MSTR  0.00022568975    MU  0.00444197151    NFLX  0.01142807504    NVDA  0.02835605467    NXPI  0.00276598739    ODFL  0.00183152924    ON  0.00131222458    ORLY  0.00256482544    PANW  0.00169402980    PAYX  0.00231073242    PCAR  0.00195357477    PDD  0.00660689107    PEP  0.01347919551    PYPL  0.01106431370    QCOM  0.00882966453    REGN  0.00419077002    ROP  0.00011811165    ROST  0.00223772066    SBUX  0.00683515402    SNPS  0.00271136567    TEAM  0.00340925304    TMUS  0.00975435576    TSLA  0.03817994959    TTD  0.00179475950    TTWO  0.00119022390    TXN  0.00930831127    VRSK  0.00183785212    VRTX  0.00418002831    WBD  0.00151564487    WDAY  0.00313075934    XEL  0.00224257674    ZS  0.00142093396
"""

# Splitting the string into parts (ticker and percentage)
split_data = ticker_percentage_string.split()
tickers = split_data[0::2]  # Extracting tickers (every second element starting from 0)
values = [float(value) for value in split_data[1::2]]  # Extracting values (every second element starting from 1)

# Creating the DataFrame with two rows: one for tickers, one for values
df = pd.DataFrame([tickers, values])

# import ace_tools as tools
# tools.display_dataframe_to_user(name="Ticker Percentages DataFrame", dataframe=df)

In [ ]:
df

,0,1,2,3,4,5,6,7,8,9,...,87,88,89,90,91,92,93,94,95,96
0,ADBE,AMD,ABNB,AAPL,ADI,ADP,ADSK,AEP,AMAT,AMGN,...,TSLA,TTD,TTWO,TXN,VRSK,VRTX,WBD,WDAY,XEL,ZS
1,0.013047,0.007445,0.004005,0.13869,0.004316,0.005156,0.003149,0.002252,0.005675,0.008262,...,0.03818,0.001795,0.00119,0.009308,0.001838,0.00418,0.001516,0.003131,0.002243,0.001421

In [ ]:
df.to_excel('index_composition.xlsx',index= True)

In [ ]:
import pandas as pd
file1 = pd.read_excel('/content/Book100.xlsx', sheet_name='Sheet2')
file1.head()
file1

,Unnamed: 0,AAPL,ABNB,ADBE,ADI,ADP,ADSK,AEP,AMAT,AMD,...,TSLA,TTD,TTWO,TXN,VRSK,VRTX,WBD,WDAY,XEL,ZS
0,AAPL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ABNB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ADBE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,WDAY,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,XEL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,ZS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
df_cleaned = file1.dropna(how='all').dropna(axis=1, how = 'all')

In [ ]:
df_cleaned

,Unnamed: 0,AAPL,ABNB,ADBE,ADI,ADP,ADSK,AEP,AMAT,AMD,...,TSLA,TTD,TTWO,TXN,VRSK,VRTX,WBD,WDAY,XEL,ZS
0,AAPL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ABNB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ADBE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,ADI,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,ADP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,VRTX,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
186,WBD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
188,WDAY,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
190,XEL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
192,ZS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
df_cleaned.rename(columns={'Unnamed: 0': 'Ticker'}, inplace=True)

# Now 'Ticker' is part of the DataFrame, not the index
print(df_cleaned.head())

  Ticker  AAPL  ABNB  ADBE  ADI  ADP  ADSK  AEP  AMAT  AMD  ...  TSLA  TTD  \
0   AAPL   0.0   0.0   0.0  0.0  0.0   0.0  0.0   0.0  0.0  ...   0.0  0.0
2   ABNB   0.0   0.0   0.0  0.0  0.0   0.0  0.0   0.0  0.0  ...   0.0  0.0
4   ADBE   0.0   0.0   0.0  0.0  0.0   0.0  0.0   0.0  0.0  ...   0.0  0.0
6    ADI   0.0   0.0   0.0  0.0  0.0   0.0  0.0   0.0  0.0  ...   0.0  0.0
8    ADP   0.0   0.0   0.0  0.0  0.0   0.0  0.0   0.0  0.0  ...   0.0  0.0

   TTWO  TXN  VRSK  VRTX  WBD  WDAY  XEL   ZS
0   0.0  0.0   0.0   0.0  0.0   0.0  0.0  0.0
2   0.0  0.0   0.0   0.0  0.0   0.0  0.0  0.0
4   0.0  0.0   0.0   0.0  0.0   0.0  0.0  0.0
6   0.0  0.0   0.0   0.0  0.0   0.0  0.0  0.0
8   0.0  0.0   0.0   0.0  0.0   0.0  0.0  0.0

[5 rows x 98 columns]

In [ ]:
tickers_listt = [
    "ADBE", "AMD", "ABNB", "AAPL", "ADI", "ADP", "ADSK", "AEP", "AMAT", "AMGN",
    "AMZN", "ANSS", "APP", "ASML", "AVGO", "AXON", "AZN", "BIIB", "BKNG", "BKR",
    "CCEP", "CDNS", "CDW", "CEG", "CHTR", "CMCSA", "COST", "CPRT", "CRWD", "CSCO",
    "CSGP", "CSX", "CTAS", "CTSH", "DDOG", "DXCM", "EA", "EXC", "FANG", "FAST",
    "FTNT", "GEHC", "GFS", "GILD", "GOOG", "GOOGL", "HON", "IDXX", "INTC", "INTU",
    "ISRG", "KDP", "KHC", "KLAC", "LRCX", "LULU", "MAR", "MCHP", "MDB", "MDLZ",
    "MELI", "META", "MNST", "MRVL", "MSFT", "MSTR", "MU", "NFLX", "NVDA", "NXPI",
    "ODFL", "ON", "ORLY", "PANW", "PAYX", "PCAR", "PDD", "PEP", "PYPL", "QCOM",
    "REGN", "ROP", "ROST", "SBUX", "SNPS", "TEAM", "TMUS", "TSLA", "TTD", "TTWO",
    "TXN", "VRSK", "VRTX", "WBD", "WDAY", "XEL", "ZS"
]

In [ ]:
# custom_order = ['VRTX', 'AAPL', 'WBD', 'ABNB', 'ADBE', 'ADI', 'ADP']
df_temp = df_cleaned[tickers_listt]
# Reordering the DataFrame based on the custom list
# df_reordered = df_cleaned.loc[tickers_listt, tickers_listt]

In [ ]:
df_temp

,ADBE,AMD,ABNB,AAPL,ADI,ADP,ADSK,AEP,AMAT,AMGN,...,TSLA,TTD,TTWO,TXN,VRSK,VRTX,WBD,WDAY,XEL,ZS
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
186,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
188,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
190,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
192,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
df_temp.loc[tickers_listt]

KeyError: "None of [Index(['ADBE', 'AMD', 'ABNB', 'AAPL', 'ADI', 'ADP', 'ADSK', 'AEP', 'AMAT',\n       'AMGN', 'AMZN', 'ANSS', 'APP', 'ASML', 'AVGO', 'AXON', 'AZN', 'BIIB',\n       'BKNG', 'BKR', 'CCEP', 'CDNS', 'CDW', 'CEG', 'CHTR', 'CMCSA', 'COST',\n       'CPRT', 'CRWD', 'CSCO', 'CSGP', 'CSX', 'CTAS', 'CTSH', 'DDOG', 'DXCM',\n       'EA', 'EXC', 'FANG', 'FAST', 'FTNT', 'GEHC', 'GFS', 'GILD', 'GOOG',\n       'GOOGL', 'HON', 'IDXX', 'INTC', 'INTU', 'ISRG', 'KDP', 'KHC', 'KLAC',\n       'LRCX', 'LULU', 'MAR', 'MCHP', 'MDB', 'MDLZ', 'MELI', 'META', 'MNST',\n       'MRVL', 'MSFT', 'MSTR', 'MU', 'NFLX', 'NVDA', 'NXPI', 'ODFL', 'ON',\n       'ORLY', 'PANW', 'PAYX', 'PCAR', 'PDD', 'PEP', 'PYPL', 'QCOM', 'REGN',\n       'ROP', 'ROST', 'SBUX', 'SNPS', 'TEAM', 'TMUS', 'TSLA', 'TTD', 'TTWO',\n       'TXN', 'VRSK', 'VRTX', 'WBD', 'WDAY', 'XEL', 'ZS'],\n      dtype='object')] are in the [index]"